version: 2
services:
  - type: web
    name: faculty-availability-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: faculty-availability-backend
          property: port
    healthCheckPath: /api/health

  - type: static
    name: faculty-availability-frontend
    staticPublishPath: ./client/build
    buildCommand: cd client && npm install && npm run build
    publishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
