import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import './QRGenerator.css';

const QRGenerator = () => {
  const { facultyId } = useParams();
  const [faculty, setFaculty] = useState(null);
  const [qrData, setQrData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [qrSize, setQrSize] = useState(300);
  const [qrFormat, setQrFormat] = useState('data');

  useEffect(() => {
    fetchQRData();
  }, [facultyId, qrSize, qrFormat]);

  const fetchQRData = async () => {
    try {
      setLoading(true);
      setError('');

      // Fetch faculty info and QR code
      const [facultyResponse, qrResponse] = await Promise.all([
        axios.get(`/faculty/${facultyId}`),
        axios.get(`/qr/${facultyId}`, {
          params: {
            format: qrFormat,
            size: qrSize
          }
        })
      ]);

      setFaculty(facultyResponse.data.faculty);
      setQrData(qrResponse.data);

    } catch (err) {
      console.error('Failed to fetch QR data:', err);
      setError(
        err.response?.status === 404 
          ? 'Faculty member not found' 
          : 'Failed to generate QR code'
      );
    } finally {
      setLoading(false);
    }
  };

  const downloadQR = () => {
    if (!qrData?.qrCode?.dataUrl) return;

    const link = document.createElement('a');
    link.href = qrData.qrCode.dataUrl;
    link.download = `faculty_${facultyId}_qr_code.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const copyQRLink = async () => {
    const url = `${window.location.origin}/check/${facultyId}`;
    try {
      await navigator.clipboard.writeText(url);
      alert('QR code link copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy:', err);
      alert('Failed to copy link. Please copy manually: ' + url);
    }
  };

  const printQR = () => {
    const printWindow = window.open('', '_blank');
    const qrImage = qrData?.qrCode?.dataUrl;
    
    if (printWindow && qrImage) {
      printWindow.document.write(`
        <html>
          <head>
            <title>QR Code - ${faculty?.name}</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 20px;
              }
              .qr-print-container {
                max-width: 400px;
                margin: 0 auto;
              }
              .qr-image {
                max-width: 100%;
                height: auto;
                border: 2px solid #333;
                border-radius: 8px;
              }
              .faculty-info {
                margin: 20px 0;
              }
              .instructions {
                font-size: 14px;
                color: #666;
                margin-top: 20px;
              }
            </style>
          </head>
          <body>
            <div class="qr-print-container">
              <h1>${faculty?.name}</h1>
              <p><strong>Department:</strong> ${faculty?.department}</p>
              ${faculty?.office_location ? `<p><strong>Office:</strong> ${faculty.office_location}</p>` : ''}
              <img src="${qrImage}" alt="QR Code" class="qr-image" />
              <div class="instructions">
                <p><strong>How to use:</strong></p>
                <p>1. Scan this QR code with your smartphone camera</p>
                <p>2. Visit the link to check real-time availability status</p>
                <p>3. Plan your visit accordingly</p>
              </div>
              <p><small>Generated by Faculty Availability System</small></p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  if (loading) {
    return (
      <div className="qr-generator">
        <div className="qr-container">
          <div className="loading-spinner">
            <div className="spinner"></div>
            <p>Generating QR code...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="qr-generator">
        <div className="qr-container">
          <div className="error-state">
            <div className="error-icon">❌</div>
            <h2>Error</h2>
            <p>{error}</p>
            <button onClick={fetchQRData} className="retry-btn">
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="qr-generator">
      <div className="qr-container">
        <div className="qr-header">
          <h1>QR Code Generator</h1>
          <p>Share your unique QR code with students to let them check your availability status instantly.</p>
        </div>

        <div className="faculty-card">
          <div className="faculty-avatar">
            {faculty?.name?.charAt(0).toUpperCase()}
          </div>
          <div className="faculty-details">
            <h2>{faculty?.name}</h2>
            <p className="department">{faculty?.department}</p>
            {faculty?.office_location && (
              <p className="office">📍 {faculty?.office_location}</p>
            )}
            <div className="current-status">
              <span className="status-label">Current Status:</span>
              <span className={`status-badge status-${faculty?.status || 0}`}>
                {['Available', 'Busy', 'Away', 'Offline'][faculty?.status || 0]}
              </span>
            </div>
          </div>
        </div>

        <div className="qr-display">
          <div className="qr-code-container">
            {qrData?.qrCode?.dataUrl && (
              <img 
                src={qrData.qrCode.dataUrl} 
                alt="Faculty QR Code"
                className="qr-image"
              />
            )}
          </div>
          
          <div className="qr-info">
            <h3>QR Code Information</h3>
            <div className="info-grid">
              <div className="info-item">
                <span className="info-label">Link:</span>
                <span className="info-value">{qrData?.qrCode?.data}</span>
              </div>
              <div className="info-item">
                <span className="info-label">Size:</span>
                <span className="info-value">{qrSize}x{qrSize} pixels</span>
              </div>
              <div className="info-item">
                <span className="info-label">Format:</span>
                <span className="info-value">PNG</span>
              </div>
            </div>
          </div>
        </div>

        <div className="qr-controls">
          <h3>Customize QR Code</h3>
          <div className="controls-grid">
            <div className="control-group">
              <label htmlFor="qrSize">Size:</label>
              <select 
                id="qrSize"
                value={qrSize} 
                onChange={(e) => setQrSize(parseInt(e.target.value))}
              >
                <option value={150}>150x150</option>
                <option value={200}>200x200</option>
                <option value={300}>300x300</option>
                <option value={400}>400x400</option>
                <option value={500}>500x500</option>
              </select>
            </div>
          </div>
        </div>

        <div className="qr-actions">
          <button onClick={downloadQR} className="action-btn primary">
            📥 Download QR Code
          </button>
          <button onClick={copyQRLink} className="action-btn secondary">
            🔗 Copy Link
          </button>
          <button onClick={printQR} className="action-btn secondary">
            🖨️ Print QR Code
          </button>
          <a 
            href={`/check/${facultyId}`} 
            target="_blank" 
            rel="noopener noreferrer"
            className="action-btn outline"
          >
            👁️ Preview Status Page
          </a>
        </div>

        <div className="usage-instructions">
          <h3>How Students Use This QR Code</h3>
          <div className="instructions-grid">
            <div className="instruction-step">
              <div className="step-number">1</div>
              <div className="step-content">
                <h4>Scan the Code</h4>
                <p>Students use their smartphone camera to scan the QR code</p>
              </div>
            </div>
            <div className="instruction-step">
              <div className="step-number">2</div>
              <div className="step-content">
                <h4>Check Status</h4>
                <p>They're redirected to your real-time availability status page</p>
              </div>
            </div>
            <div className="instruction-step">
              <div className="step-number">3</div>
              <div className="step-content">
                <h4>Plan Visit</h4>
                <p>Students can decide whether to visit based on your current status</p>
              </div>
            </div>
          </div>
        </div>

        <div className="sharing-tips">
          <h3>Sharing Tips</h3>
          <ul>
            <li>Print and place the QR code outside your office door</li>
            <li>Include it in your email signature</li>
            <li>Add it to your course materials or syllabus</li>
            <li>Share it on your department's website</li>
            <li>Post it on your office hours announcement</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default QRGenerator;
